/*
 * İlk kurulum verileri - tablolar boşken otomatik yüklenir (bkz. bootstrap.ts).
 * seed-db.mjs ve seed-superbox.mjs ile aynı içerik.
 */
import type { InsertPhone, InsertPackage, InsertAccessory, InsertSuperbox } from "../drizzle/schema";

export const phonesSeed: InsertPhone[] = [
  { slug: "iphone-16-pro-max", name: "iPhone 16 Pro Max", brand: "Apple", price: 84999, oldPrice: 89999, image: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=400&h=500&fit=crop", storage: "256 GB", ram: "8 GB", screen: "6.9 inç OLED", camera: "48 MP + 12 MP + 48 MP", battery: "4685 mAh", color: "Titan Siyah", badge: "Yeni", installment: "12 Taksit", sortOrder: 1 },
  { slug: "iphone-16", name: "iPhone 16", brand: "Apple", price: 59999, oldPrice: 64999, image: "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=400&h=500&fit=crop", storage: "128 GB", ram: "8 GB", screen: "6.1 inç OLED", camera: "48 MP + 12 MP", battery: "3561 mAh", color: "Mavi", badge: "Popüler", installment: "12 Taksit", sortOrder: 2 },
  { slug: "samsung-galaxy-s25-ultra", name: "Samsung Galaxy S25 Ultra", brand: "Samsung", price: 74999, oldPrice: 79999, image: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=400&h=500&fit=crop", storage: "256 GB", ram: "12 GB", screen: "6.8 inç Dynamic AMOLED", camera: "200 MP + 50 MP + 10 MP + 12 MP", battery: "5000 mAh", color: "Titan Gri", badge: "Çok Satan", installment: "12 Taksit", sortOrder: 3 },
  { slug: "samsung-galaxy-a16", name: "Samsung Galaxy A16", brand: "Samsung", price: 12999, oldPrice: null, image: "https://images.unsplash.com/photo-1585060544812-6b45742d762f?w=400&h=500&fit=crop", storage: "128 GB", ram: "4 GB", screen: "6.5 inç AMOLED", camera: "50 MP + 5 MP + 2 MP", battery: "5000 mAh", color: "Siyah", badge: null, installment: "6 Taksit", sortOrder: 4 },
  { slug: "xiaomi-redmi-note-15-pro", name: "Xiaomi Redmi Note 15 Pro", brand: "Xiaomi", price: 17999, oldPrice: 19999, image: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=400&h=500&fit=crop", storage: "256 GB", ram: "8 GB", screen: "6.67 inç AMOLED", camera: "200 MP + 8 MP + 2 MP", battery: "5110 mAh", color: "Mavi", badge: "Fiyat/Performans", installment: "9 Taksit", sortOrder: 5 },
  { slug: "samsung-galaxy-s25", name: "Samsung Galaxy S25", brand: "Samsung", price: 49999, oldPrice: null, image: "https://images.unsplash.com/photo-1556656793-08538906a9f8?w=400&h=500&fit=crop", storage: "128 GB", ram: "8 GB", screen: "6.2 inç Dynamic AMOLED", camera: "50 MP + 12 MP + 10 MP", battery: "4000 mAh", color: "Lacivert", badge: null, installment: "12 Taksit", sortOrder: 6 },
  { slug: "iphone-15", name: "iPhone 15", brand: "Apple", price: 44999, oldPrice: 49999, image: "https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=400&h=500&fit=crop", storage: "128 GB", ram: "6 GB", screen: "6.1 inç OLED", camera: "48 MP + 12 MP", battery: "3349 mAh", color: "Pembe", badge: "İndirimli", installment: "12 Taksit", sortOrder: 7 },
  { slug: "xiaomi-15", name: "Xiaomi 15", brand: "Xiaomi", price: 37999, oldPrice: null, image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=500&fit=crop", storage: "256 GB", ram: "12 GB", screen: "6.36 inç AMOLED", camera: "50 MP + 50 MP + 50 MP", battery: "5400 mAh", color: "Siyah", badge: "Yeni", installment: "9 Taksit", sortOrder: 8 },
];

export const packagesSeed: InsertPackage[] = [
  { slug: "esneyen-paket", name: "Esneyen Paket", category: "faturali", internet: "5 GB", minutes: "1500 dk", sms: "250 SMS", price: 430, popular: false, features: JSON.stringify(["Esnek kullanım", "Turkcell uygulamaları dahil"]), sortOrder: 1 },
  { slug: "star-5gb", name: "Star+ 5 GB", category: "faturali", internet: "5 GB", minutes: "1000 dk", sms: "250 SMS", price: 550, popular: false, features: JSON.stringify(["BiP ücretsiz", "TV+ dahil"]), sortOrder: 2 },
  { slug: "star-10gb", name: "Star+ 10 GB", category: "faturali", internet: "10 GB", minutes: "1000 dk", sms: "250 SMS", price: 650, popular: false, features: JSON.stringify(["BiP ücretsiz", "TV+ dahil", "fizy müzik"]), sortOrder: 3 },
  { slug: "star-15gb", name: "Star+ 15 GB", category: "faturali", internet: "15 GB", minutes: "1000 dk", sms: "250 SMS", price: 750, popular: true, features: JSON.stringify(["BiP ücretsiz", "TV+ dahil", "fizy müzik", "Dergilik"]), sortOrder: 4 },
  { slug: "star-20gb", name: "Star+ 20 GB", category: "faturali", internet: "20 GB", minutes: "1000 dk", sms: "500 SMS", price: 900, popular: false, features: JSON.stringify(["BiP ücretsiz", "TV+ dahil", "fizy müzik", "Dergilik"]), sortOrder: 5 },
  { slug: "star-30gb", name: "Star+ 30 GB", category: "faturali", internet: "30 GB", minutes: "2000 dk", sms: "500 SMS", price: 1100, popular: true, features: JSON.stringify(["BiP ücretsiz", "TV+ dahil", "fizy müzik", "Dergilik", "Platinum avantajları"]), sortOrder: 6 },
  { slug: "star-40gb", name: "Star+ 40 GB", category: "faturali", internet: "40 GB", minutes: "2000 dk", sms: "500 SMS", price: 1200, popular: false, features: JSON.stringify(["BiP ücretsiz", "TV+ dahil", "fizy müzik", "Dergilik", "Platinum avantajları"]), sortOrder: 7 },
  { slug: "platinum-60gb", name: "Platinum+ 60 GB", category: "faturali", internet: "60 GB", minutes: "3000 dk", sms: "1000 SMS", price: 1400, popular: false, features: JSON.stringify(["Tüm Turkcell uygulamaları", "Yurt dışı kullanım", "Öncelikli müşteri hizmetleri"]), sortOrder: 8 },
  { slug: "platinum-black-120gb", name: "Platinum+ Black 120 GB", category: "faturali", internet: "120 GB", minutes: "3000 dk", sms: "1000 SMS", price: 2000, popular: false, features: JSON.stringify(["Tüm Turkcell uygulamaları", "Yurt dışı kullanım", "VIP müşteri hizmetleri", "Lounge erişimi"]), sortOrder: 9 },
  { slug: "gnc-10gb", name: "GNÇ+ 10 GB", category: "genc", internet: "10 GB", minutes: "1000 dk", sms: "300 SMS", price: 500, popular: true, features: JSON.stringify(["Sosyal medya paketi", "Spotify ücretsiz", "GNÇ avantajları"]), sortOrder: 10 },
  { slug: "gnc-20gb", name: "GNÇ+ 20 GB", category: "genc", internet: "20 GB", minutes: "1000 dk", sms: "300 SMS", price: 650, popular: false, features: JSON.stringify(["Sosyal medya paketi", "Spotify ücretsiz", "GNÇ avantajları", "YouTube Premium"]), sortOrder: 11 },
  { slug: "gnc-30gb", name: "GNÇ+ 30 GB", category: "genc", internet: "30 GB", minutes: "1000 dk", sms: "300 SMS", price: 800, popular: false, features: JSON.stringify(["Sosyal medya paketi", "Spotify ücretsiz", "GNÇ avantajları", "YouTube Premium", "Netflix"]), sortOrder: 12 },
  { slug: "gnc-50gb", name: "GNÇ+ 50 GB", category: "genc", internet: "50 GB", minutes: "1000 dk", sms: "300 SMS", price: 1050, popular: false, features: JSON.stringify(["Sosyal medya paketi", "Spotify ücretsiz", "GNÇ avantajları", "YouTube Premium", "Netflix", "Oyun paketi"]), sortOrder: 13 },
];

export const accessoriesSeed: InsertAccessory[] = [
  { slug: "apple-airpods-pro-2", name: "Apple AirPods Pro 2", category: "Kulaklık", price: 8999, image: "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=300&h=300&fit=crop", brand: "Apple", sortOrder: 1 },
  { slug: "samsung-galaxy-buds3-pro", name: "Samsung Galaxy Buds3 Pro", category: "Kulaklık", price: 6999, image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=300&h=300&fit=crop", brand: "Samsung", sortOrder: 2 },
  { slug: "anker-powercore-20000", name: "Anker PowerCore 20000", category: "Powerbank", price: 1299, image: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=300&h=300&fit=crop", brand: "Anker", sortOrder: 3 },
  { slug: "spigen-ultra-hybrid-kilif", name: "Spigen Ultra Hybrid Kılıf", category: "Kılıf", price: 499, image: "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=300&h=300&fit=crop", brand: "Spigen", sortOrder: 4 },
  { slug: "belkin-magsafe-sarj", name: "Belkin MagSafe Şarj Cihazı", category: "Şarj", price: 1899, image: "https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=300&h=300&fit=crop", brand: "Belkin", sortOrder: 5 },
  { slug: "apple-watch-se", name: "Apple Watch SE", category: "Akıllı Saat", price: 12999, image: "https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=300&h=300&fit=crop", brand: "Apple", sortOrder: 6 },
];

export const superboxSeed: InsertSuperbox[] = [
  { slug: "superbox-5g-hazir-250gb", name: "Superbox 5G Hazır 250 GB", category: "5g-hazir", speed: "4.5G", quota: "250 GB", commitment: "12 Ay", price: 1100, bonus: null, bonusDetail: null, isOnlineExclusive: false, popular: false, sortOrder: 1 },
  { slug: "superbox-5g-hazir-500gb", name: "Superbox 5G Hazır 500 GB", category: "5g-hazir", speed: "4.5G", quota: "500 GB", commitment: "12 Ay", price: 1350, bonus: null, bonusDetail: null, isOnlineExclusive: false, popular: true, sortOrder: 2 },
  { slug: "superbox-5g-hazir-1tb", name: "Superbox 5G Hazır 1 TB", category: "5g-hazir", speed: "4.5G", quota: "1 TB", commitment: "12 Ay", price: 1850, bonus: null, bonusDetail: null, isOnlineExclusive: false, popular: false, sortOrder: 3 },
  { slug: "superbox-devam-200gb", name: "Superbox Devam 200 GB", category: "devam", speed: "4.5G", quota: "200 GB", commitment: "12 Ay", price: 1000, bonus: "50 GB Hediye", bonusDetail: "12 Ay Boyunca Her Ay Hediye", isOnlineExclusive: false, popular: false, sortOrder: 4 },
  { slug: "superbox-devam-500gb", name: "Superbox Devam 500 GB", category: "devam", speed: "4.5G", quota: "500 GB", commitment: "12 Ay", price: 1250, bonus: null, bonusDetail: null, isOnlineExclusive: false, popular: true, sortOrder: 5 },
  { slug: "superbox-devam-1tb", name: "Superbox Devam 1 TB", category: "devam", speed: "4.5G", quota: "1 TB", commitment: "12 Ay", price: 1750, bonus: null, bonusDetail: null, isOnlineExclusive: false, popular: false, sortOrder: 6 },
  { slug: "superbox-devam-2tb", name: "Superbox Devam 2 TB", category: "devam", speed: "4.5G", quota: "2 TB", commitment: "12 Ay", price: 2500, bonus: null, bonusDetail: null, isOnlineExclusive: false, popular: false, sortOrder: 7 },
  { slug: "superbox-calistir-devam-200gb", name: "Superbox Çalıştır Devam 200 GB", category: "calistir-devam", speed: "4.5G", quota: "200 GB", commitment: "12 Ay", price: 1000, bonus: null, bonusDetail: "12 Ay Boyunca Her Ay Hediye", isOnlineExclusive: false, popular: false, sortOrder: 8 },
  { slug: "superbox-calistir-devam-500gb", name: "Superbox Çalıştır Devam 500 GB", category: "calistir-devam", speed: "4.5G", quota: "500 GB", commitment: "12 Ay", price: 1250, bonus: null, bonusDetail: null, isOnlineExclusive: false, popular: false, sortOrder: 9 },
  { slug: "superbox-calistir-devam-1tb", name: "Superbox Çalıştır Devam 1 TB", category: "calistir-devam", speed: "4.5G", quota: "1 TB", commitment: "12 Ay", price: 1750, bonus: null, bonusDetail: null, isOnlineExclusive: false, popular: false, sortOrder: 10 },
  { slug: "superbox-calistir-devam-2tb", name: "Superbox Çalıştır Devam 2 TB", category: "calistir-devam", speed: "4.5G", quota: "2 TB", commitment: "12 Ay", price: 2500, bonus: null, bonusDetail: null, isOnlineExclusive: false, popular: false, sortOrder: 11 },
  { slug: "superbox-dijitale-ozel-100gb", name: "Superbox Dijitale Özel 100 GB", category: "dijitale-ozel", speed: "4.5G", quota: "100 GB", commitment: "12 Ay", price: 690, bonus: null, bonusDetail: "12 Ay Boyunca Her Ay Hediye", isOnlineExclusive: true, popular: true, sortOrder: 12 },
  { slug: "superbox-dijitale-ozel-300gb", name: "Superbox Dijitale Özel 300 GB", category: "dijitale-ozel", speed: "4.5G", quota: "300 GB", commitment: "12 Ay", price: 1000, bonus: null, bonusDetail: "12 Ay Boyunca Her Ay Hediye", isOnlineExclusive: true, popular: false, sortOrder: 13 },
  { slug: "superbox-dijitale-ozel-1tb", name: "Superbox Dijitale Özel 1 TB", category: "dijitale-ozel", speed: "4.5G", quota: "1 TB", commitment: "12 Ay", price: 1700, bonus: null, bonusDetail: "12 Ay Boyunca Her Ay Hediye", isOnlineExclusive: true, popular: false, sortOrder: 14 },
  { slug: "superbox-dijitale-ozel-2tb", name: "Superbox Dijitale Özel 2 TB", category: "dijitale-ozel", speed: "4.5G", quota: "2 TB", commitment: "12 Ay", price: 2800, bonus: null, bonusDetail: "12 Ay Boyunca Her Ay Hediye", isOnlineExclusive: true, popular: false, sortOrder: 15 },
  { slug: "superbox-4-5g-100gb", name: "Superbox 4.5G 100 GB", category: "4-5g", speed: "4.5G", quota: "100 GB", commitment: "12 Ay", price: 690, bonus: null, bonusDetail: "12 Ay Boyunca Her Ay Hediye", isOnlineExclusive: false, popular: false, sortOrder: 16 },
  { slug: "superbox-4-5g-300gb", name: "Superbox 4.5G 300 GB", category: "4-5g", speed: "4.5G", quota: "300 GB", commitment: "12 Ay", price: 1000, bonus: null, bonusDetail: "12 Ay Boyunca Her Ay Hediye", isOnlineExclusive: false, popular: false, sortOrder: 17 },
  { slug: "superbox-4-5g-1tb", name: "Superbox 4.5G 1 TB", category: "4-5g", speed: "4.5G", quota: "1 TB", commitment: "12 Ay", price: 1700, bonus: null, bonusDetail: null, isOnlineExclusive: false, popular: false, sortOrder: 18 },
  { slug: "superbox-4-5g-2tb", name: "Superbox 4.5G 2 TB", category: "4-5g", speed: "4.5G", quota: "2 TB", commitment: "12 Ay", price: 2800, bonus: null, bonusDetail: null, isOnlineExclusive: false, popular: false, sortOrder: 19 },
];
